"""empty message

Revision ID: fb8e8cf3d12e
Revises: 807c73855c5a
Create Date: 2022-12-22 21:13:06.171007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8e8cf3d12e'
down_revision = '807c73855c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('savings')

    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'goal', ['goal'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('goal')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savings', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'savings', ['savings'], ['id'])

    # ### end Alembic commands ###
